// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package vehiclelookup.proxies;

/**
 * 
 */
public class dataObj
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dataObjMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "VehicleLookUp.dataObj";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		data("VehicleLookUp.data"),
		vehicle_information("VehicleLookUp.vehicle_information"),
		vehicle_specification("VehicleLookUp.vehicle_specification"),
		dvla_vehicle_information("VehicleLookUp.dvla_vehicle_information"),
		mot_history("VehicleLookUp.mot_history");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public dataObj(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "VehicleLookUp.dataObj"));
	}

	protected dataObj(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dataObjMendixObject)
	{
		if (dataObjMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("VehicleLookUp.dataObj", dataObjMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a VehicleLookUp.dataObj");

		this.dataObjMendixObject = dataObjMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'dataObj.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static vehiclelookup.proxies.dataObj initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return vehiclelookup.proxies.dataObj.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static vehiclelookup.proxies.dataObj initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new vehiclelookup.proxies.dataObj(context, mendixObject);
	}

	public static vehiclelookup.proxies.dataObj load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return vehiclelookup.proxies.dataObj.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of data
	 */
	public final vehiclelookup.proxies.ResponseObj getdata() throws com.mendix.core.CoreException
	{
		return getdata(getContext());
	}

	/**
	 * @param context
	 * @return value of data
	 */
	public final vehiclelookup.proxies.ResponseObj getdata(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		vehiclelookup.proxies.ResponseObj result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.data.toString());
		if (identifier != null)
			result = vehiclelookup.proxies.ResponseObj.load(context, identifier);
		return result;
	}

	/**
	 * Set value of data
	 * @param data
	 */
	public final void setdata(vehiclelookup.proxies.ResponseObj data)
	{
		setdata(getContext(), data);
	}

	/**
	 * Set value of data
	 * @param context
	 * @param data
	 */
	public final void setdata(com.mendix.systemwideinterfaces.core.IContext context, vehiclelookup.proxies.ResponseObj data)
	{
		if (data == null)
			getMendixObject().setValue(context, MemberNames.data.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.data.toString(), data.getMendixObject().getId());
	}

	/**
	 * @return value of vehicle_information
	 */
	public final vehiclelookup.proxies.VehicleObj getvehicle_information() throws com.mendix.core.CoreException
	{
		return getvehicle_information(getContext());
	}

	/**
	 * @param context
	 * @return value of vehicle_information
	 */
	public final vehiclelookup.proxies.VehicleObj getvehicle_information(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		vehiclelookup.proxies.VehicleObj result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.vehicle_information.toString());
		if (identifier != null)
			result = vehiclelookup.proxies.VehicleObj.load(context, identifier);
		return result;
	}

	/**
	 * Set value of vehicle_information
	 * @param vehicle_information
	 */
	public final void setvehicle_information(vehiclelookup.proxies.VehicleObj vehicle_information)
	{
		setvehicle_information(getContext(), vehicle_information);
	}

	/**
	 * Set value of vehicle_information
	 * @param context
	 * @param vehicle_information
	 */
	public final void setvehicle_information(com.mendix.systemwideinterfaces.core.IContext context, vehiclelookup.proxies.VehicleObj vehicle_information)
	{
		if (vehicle_information == null)
			getMendixObject().setValue(context, MemberNames.vehicle_information.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.vehicle_information.toString(), vehicle_information.getMendixObject().getId());
	}

	/**
	 * @return value of vehicle_specification
	 */
	public final vehiclelookup.proxies.VehicleSpecificationObj getvehicle_specification() throws com.mendix.core.CoreException
	{
		return getvehicle_specification(getContext());
	}

	/**
	 * @param context
	 * @return value of vehicle_specification
	 */
	public final vehiclelookup.proxies.VehicleSpecificationObj getvehicle_specification(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		vehiclelookup.proxies.VehicleSpecificationObj result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.vehicle_specification.toString());
		if (identifier != null)
			result = vehiclelookup.proxies.VehicleSpecificationObj.load(context, identifier);
		return result;
	}

	/**
	 * Set value of vehicle_specification
	 * @param vehicle_specification
	 */
	public final void setvehicle_specification(vehiclelookup.proxies.VehicleSpecificationObj vehicle_specification)
	{
		setvehicle_specification(getContext(), vehicle_specification);
	}

	/**
	 * Set value of vehicle_specification
	 * @param context
	 * @param vehicle_specification
	 */
	public final void setvehicle_specification(com.mendix.systemwideinterfaces.core.IContext context, vehiclelookup.proxies.VehicleSpecificationObj vehicle_specification)
	{
		if (vehicle_specification == null)
			getMendixObject().setValue(context, MemberNames.vehicle_specification.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.vehicle_specification.toString(), vehicle_specification.getMendixObject().getId());
	}

	/**
	 * @return value of dvla_vehicle_information
	 */
	public final vehiclelookup.proxies.DvlaVehicleInformationObj getdvla_vehicle_information() throws com.mendix.core.CoreException
	{
		return getdvla_vehicle_information(getContext());
	}

	/**
	 * @param context
	 * @return value of dvla_vehicle_information
	 */
	public final vehiclelookup.proxies.DvlaVehicleInformationObj getdvla_vehicle_information(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		vehiclelookup.proxies.DvlaVehicleInformationObj result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.dvla_vehicle_information.toString());
		if (identifier != null)
			result = vehiclelookup.proxies.DvlaVehicleInformationObj.load(context, identifier);
		return result;
	}

	/**
	 * Set value of dvla_vehicle_information
	 * @param dvla_vehicle_information
	 */
	public final void setdvla_vehicle_information(vehiclelookup.proxies.DvlaVehicleInformationObj dvla_vehicle_information)
	{
		setdvla_vehicle_information(getContext(), dvla_vehicle_information);
	}

	/**
	 * Set value of dvla_vehicle_information
	 * @param context
	 * @param dvla_vehicle_information
	 */
	public final void setdvla_vehicle_information(com.mendix.systemwideinterfaces.core.IContext context, vehiclelookup.proxies.DvlaVehicleInformationObj dvla_vehicle_information)
	{
		if (dvla_vehicle_information == null)
			getMendixObject().setValue(context, MemberNames.dvla_vehicle_information.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.dvla_vehicle_information.toString(), dvla_vehicle_information.getMendixObject().getId());
	}

	/**
	 * @return value of mot_history
	 */
	public final java.util.List<vehiclelookup.proxies.MOTHistoryObj> getmot_history() throws com.mendix.core.CoreException
	{
		return getmot_history(getContext());
	}

	/**
	 * @param context
	 * @return value of mot_history
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<vehiclelookup.proxies.MOTHistoryObj> getmot_history(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<vehiclelookup.proxies.MOTHistoryObj> result = new java.util.ArrayList<vehiclelookup.proxies.MOTHistoryObj>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.mot_history.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(vehiclelookup.proxies.MOTHistoryObj.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of mot_history
	 * @param mot_history
	 */
	public final void setmot_history(java.util.List<vehiclelookup.proxies.MOTHistoryObj> mot_history)
	{
		setmot_history(getContext(), mot_history);
	}

	/**
	 * Set value of mot_history
	 * @param context
	 * @param mot_history
	 */
	public final void setmot_history(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<vehiclelookup.proxies.MOTHistoryObj> mot_history)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (vehiclelookup.proxies.MOTHistoryObj proxyObject : mot_history)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.mot_history.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dataObjMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final vehiclelookup.proxies.dataObj that = (vehiclelookup.proxies.dataObj) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "VehicleLookUp.dataObj";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
