// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package vehiclelookup.proxies;

/**
 * 
 */
public class DvlaVehicleInformationObj
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dvlaVehicleInformationObjMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "VehicleLookUp.DvlaVehicleInformationObj";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		dvla_vehicle_information("VehicleLookUp.dvla_vehicle_information"),
		tax("VehicleLookUp.tax"),
		mot("VehicleLookUp.mot");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DvlaVehicleInformationObj(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "VehicleLookUp.DvlaVehicleInformationObj"));
	}

	protected DvlaVehicleInformationObj(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dvlaVehicleInformationObjMendixObject)
	{
		if (dvlaVehicleInformationObjMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("VehicleLookUp.DvlaVehicleInformationObj", dvlaVehicleInformationObjMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a VehicleLookUp.DvlaVehicleInformationObj");

		this.dvlaVehicleInformationObjMendixObject = dvlaVehicleInformationObjMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DvlaVehicleInformationObj.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static vehiclelookup.proxies.DvlaVehicleInformationObj initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return vehiclelookup.proxies.DvlaVehicleInformationObj.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static vehiclelookup.proxies.DvlaVehicleInformationObj initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new vehiclelookup.proxies.DvlaVehicleInformationObj(context, mendixObject);
	}

	public static vehiclelookup.proxies.DvlaVehicleInformationObj load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return vehiclelookup.proxies.DvlaVehicleInformationObj.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of dvla_vehicle_information
	 */
	public final vehiclelookup.proxies.dataObj getdvla_vehicle_information() throws com.mendix.core.CoreException
	{
		return getdvla_vehicle_information(getContext());
	}

	/**
	 * @param context
	 * @return value of dvla_vehicle_information
	 */
	public final vehiclelookup.proxies.dataObj getdvla_vehicle_information(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		vehiclelookup.proxies.dataObj result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.dvla_vehicle_information.toString());
		if (identifier != null)
			result = vehiclelookup.proxies.dataObj.load(context, identifier);
		return result;
	}

	/**
	 * Set value of dvla_vehicle_information
	 * @param dvla_vehicle_information
	 */
	public final void setdvla_vehicle_information(vehiclelookup.proxies.dataObj dvla_vehicle_information)
	{
		setdvla_vehicle_information(getContext(), dvla_vehicle_information);
	}

	/**
	 * Set value of dvla_vehicle_information
	 * @param context
	 * @param dvla_vehicle_information
	 */
	public final void setdvla_vehicle_information(com.mendix.systemwideinterfaces.core.IContext context, vehiclelookup.proxies.dataObj dvla_vehicle_information)
	{
		if (dvla_vehicle_information == null)
			getMendixObject().setValue(context, MemberNames.dvla_vehicle_information.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.dvla_vehicle_information.toString(), dvla_vehicle_information.getMendixObject().getId());
	}

	/**
	 * @return value of tax
	 */
	public final vehiclelookup.proxies.TaxObj gettax() throws com.mendix.core.CoreException
	{
		return gettax(getContext());
	}

	/**
	 * @param context
	 * @return value of tax
	 */
	public final vehiclelookup.proxies.TaxObj gettax(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		vehiclelookup.proxies.TaxObj result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.tax.toString());
		if (identifier != null)
			result = vehiclelookup.proxies.TaxObj.load(context, identifier);
		return result;
	}

	/**
	 * Set value of tax
	 * @param tax
	 */
	public final void settax(vehiclelookup.proxies.TaxObj tax)
	{
		settax(getContext(), tax);
	}

	/**
	 * Set value of tax
	 * @param context
	 * @param tax
	 */
	public final void settax(com.mendix.systemwideinterfaces.core.IContext context, vehiclelookup.proxies.TaxObj tax)
	{
		if (tax == null)
			getMendixObject().setValue(context, MemberNames.tax.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.tax.toString(), tax.getMendixObject().getId());
	}

	/**
	 * @return value of mot
	 */
	public final vehiclelookup.proxies.MOTObj getmot() throws com.mendix.core.CoreException
	{
		return getmot(getContext());
	}

	/**
	 * @param context
	 * @return value of mot
	 */
	public final vehiclelookup.proxies.MOTObj getmot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		vehiclelookup.proxies.MOTObj result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.mot.toString());
		if (identifier != null)
			result = vehiclelookup.proxies.MOTObj.load(context, identifier);
		return result;
	}

	/**
	 * Set value of mot
	 * @param mot
	 */
	public final void setmot(vehiclelookup.proxies.MOTObj mot)
	{
		setmot(getContext(), mot);
	}

	/**
	 * Set value of mot
	 * @param context
	 * @param mot
	 */
	public final void setmot(com.mendix.systemwideinterfaces.core.IContext context, vehiclelookup.proxies.MOTObj mot)
	{
		if (mot == null)
			getMendixObject().setValue(context, MemberNames.mot.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.mot.toString(), mot.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dvlaVehicleInformationObjMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final vehiclelookup.proxies.DvlaVehicleInformationObj that = (vehiclelookup.proxies.DvlaVehicleInformationObj) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "VehicleLookUp.DvlaVehicleInformationObj";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
