// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package vehiclelookup.proxies;

/**
 * 
 */
public class MOTObj
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mOTObjMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "VehicleLookUp.MOTObj";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		valid("valid"),
		expires("expires"),
		mot("VehicleLookUp.mot");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MOTObj(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "VehicleLookUp.MOTObj"));
	}

	protected MOTObj(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mOTObjMendixObject)
	{
		if (mOTObjMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("VehicleLookUp.MOTObj", mOTObjMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a VehicleLookUp.MOTObj");

		this.mOTObjMendixObject = mOTObjMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MOTObj.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static vehiclelookup.proxies.MOTObj initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return vehiclelookup.proxies.MOTObj.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static vehiclelookup.proxies.MOTObj initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new vehiclelookup.proxies.MOTObj(context, mendixObject);
	}

	public static vehiclelookup.proxies.MOTObj load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return vehiclelookup.proxies.MOTObj.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of valid
	 */
	public final Boolean getvalid()
	{
		return getvalid(getContext());
	}

	/**
	 * @param context
	 * @return value of valid
	 */
	public final Boolean getvalid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.valid.toString());
	}

	/**
	 * Set value of valid
	 * @param valid
	 */
	public final void setvalid(Boolean valid)
	{
		setvalid(getContext(), valid);
	}

	/**
	 * Set value of valid
	 * @param context
	 * @param valid
	 */
	public final void setvalid(com.mendix.systemwideinterfaces.core.IContext context, Boolean valid)
	{
		getMendixObject().setValue(context, MemberNames.valid.toString(), valid);
	}

	/**
	 * @return value of expires
	 */
	public final String getexpires()
	{
		return getexpires(getContext());
	}

	/**
	 * @param context
	 * @return value of expires
	 */
	public final String getexpires(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.expires.toString());
	}

	/**
	 * Set value of expires
	 * @param expires
	 */
	public final void setexpires(String expires)
	{
		setexpires(getContext(), expires);
	}

	/**
	 * Set value of expires
	 * @param context
	 * @param expires
	 */
	public final void setexpires(com.mendix.systemwideinterfaces.core.IContext context, String expires)
	{
		getMendixObject().setValue(context, MemberNames.expires.toString(), expires);
	}

	/**
	 * @return value of mot
	 */
	public final vehiclelookup.proxies.DvlaVehicleInformationObj getmot() throws com.mendix.core.CoreException
	{
		return getmot(getContext());
	}

	/**
	 * @param context
	 * @return value of mot
	 */
	public final vehiclelookup.proxies.DvlaVehicleInformationObj getmot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		vehiclelookup.proxies.DvlaVehicleInformationObj result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.mot.toString());
		if (identifier != null)
			result = vehiclelookup.proxies.DvlaVehicleInformationObj.load(context, identifier);
		return result;
	}

	/**
	 * Set value of mot
	 * @param mot
	 */
	public final void setmot(vehiclelookup.proxies.DvlaVehicleInformationObj mot)
	{
		setmot(getContext(), mot);
	}

	/**
	 * Set value of mot
	 * @param context
	 * @param mot
	 */
	public final void setmot(com.mendix.systemwideinterfaces.core.IContext context, vehiclelookup.proxies.DvlaVehicleInformationObj mot)
	{
		if (mot == null)
			getMendixObject().setValue(context, MemberNames.mot.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.mot.toString(), mot.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mOTObjMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final vehiclelookup.proxies.MOTObj that = (vehiclelookup.proxies.MOTObj) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "VehicleLookUp.MOTObj";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
