// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package vehiclelookup.proxies;

/**
 * 
 */
public class RequestResponseObj
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject requestResponseObjMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "VehicleLookUp.RequestResponseObj";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		date_time("date_time"),
		remaining_credit_balance("remaining_credit_balance"),
		error("error"),
		request("VehicleLookUp.request");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RequestResponseObj(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "VehicleLookUp.RequestResponseObj"));
	}

	protected RequestResponseObj(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject requestResponseObjMendixObject)
	{
		if (requestResponseObjMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("VehicleLookUp.RequestResponseObj", requestResponseObjMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a VehicleLookUp.RequestResponseObj");

		this.requestResponseObjMendixObject = requestResponseObjMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'RequestResponseObj.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static vehiclelookup.proxies.RequestResponseObj initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return vehiclelookup.proxies.RequestResponseObj.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static vehiclelookup.proxies.RequestResponseObj initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new vehiclelookup.proxies.RequestResponseObj(context, mendixObject);
	}

	public static vehiclelookup.proxies.RequestResponseObj load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return vehiclelookup.proxies.RequestResponseObj.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of date_time
	 */
	public final String getdate_time()
	{
		return getdate_time(getContext());
	}

	/**
	 * @param context
	 * @return value of date_time
	 */
	public final String getdate_time(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.date_time.toString());
	}

	/**
	 * Set value of date_time
	 * @param date_time
	 */
	public final void setdate_time(String date_time)
	{
		setdate_time(getContext(), date_time);
	}

	/**
	 * Set value of date_time
	 * @param context
	 * @param date_time
	 */
	public final void setdate_time(com.mendix.systemwideinterfaces.core.IContext context, String date_time)
	{
		getMendixObject().setValue(context, MemberNames.date_time.toString(), date_time);
	}

	/**
	 * @return value of remaining_credit_balance
	 */
	public final Integer getremaining_credit_balance()
	{
		return getremaining_credit_balance(getContext());
	}

	/**
	 * @param context
	 * @return value of remaining_credit_balance
	 */
	public final Integer getremaining_credit_balance(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.remaining_credit_balance.toString());
	}

	/**
	 * Set value of remaining_credit_balance
	 * @param remaining_credit_balance
	 */
	public final void setremaining_credit_balance(Integer remaining_credit_balance)
	{
		setremaining_credit_balance(getContext(), remaining_credit_balance);
	}

	/**
	 * Set value of remaining_credit_balance
	 * @param context
	 * @param remaining_credit_balance
	 */
	public final void setremaining_credit_balance(com.mendix.systemwideinterfaces.core.IContext context, Integer remaining_credit_balance)
	{
		getMendixObject().setValue(context, MemberNames.remaining_credit_balance.toString(), remaining_credit_balance);
	}

	/**
	 * @return value of error
	 */
	public final String geterror()
	{
		return geterror(getContext());
	}

	/**
	 * @param context
	 * @return value of error
	 */
	public final String geterror(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.error.toString());
	}

	/**
	 * Set value of error
	 * @param error
	 */
	public final void seterror(String error)
	{
		seterror(getContext(), error);
	}

	/**
	 * Set value of error
	 * @param context
	 * @param error
	 */
	public final void seterror(com.mendix.systemwideinterfaces.core.IContext context, String error)
	{
		getMendixObject().setValue(context, MemberNames.error.toString(), error);
	}

	/**
	 * @return value of request
	 */
	public final vehiclelookup.proxies.ResponseObj getrequest() throws com.mendix.core.CoreException
	{
		return getrequest(getContext());
	}

	/**
	 * @param context
	 * @return value of request
	 */
	public final vehiclelookup.proxies.ResponseObj getrequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		vehiclelookup.proxies.ResponseObj result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.request.toString());
		if (identifier != null)
			result = vehiclelookup.proxies.ResponseObj.load(context, identifier);
		return result;
	}

	/**
	 * Set value of request
	 * @param request
	 */
	public final void setrequest(vehiclelookup.proxies.ResponseObj request)
	{
		setrequest(getContext(), request);
	}

	/**
	 * Set value of request
	 * @param context
	 * @param request
	 */
	public final void setrequest(com.mendix.systemwideinterfaces.core.IContext context, vehiclelookup.proxies.ResponseObj request)
	{
		if (request == null)
			getMendixObject().setValue(context, MemberNames.request.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.request.toString(), request.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return requestResponseObjMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final vehiclelookup.proxies.RequestResponseObj that = (vehiclelookup.proxies.RequestResponseObj) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "VehicleLookUp.RequestResponseObj";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
