// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package vehiclelookup.proxies;

/**
 * 
 */
public class ResponseObj
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject responseObjMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "VehicleLookUp.ResponseObj";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		request("VehicleLookUp.request"),
		data("VehicleLookUp.data");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResponseObj(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "VehicleLookUp.ResponseObj"));
	}

	protected ResponseObj(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject responseObjMendixObject)
	{
		if (responseObjMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("VehicleLookUp.ResponseObj", responseObjMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a VehicleLookUp.ResponseObj");

		this.responseObjMendixObject = responseObjMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ResponseObj.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static vehiclelookup.proxies.ResponseObj initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return vehiclelookup.proxies.ResponseObj.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static vehiclelookup.proxies.ResponseObj initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new vehiclelookup.proxies.ResponseObj(context, mendixObject);
	}

	public static vehiclelookup.proxies.ResponseObj load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return vehiclelookup.proxies.ResponseObj.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of request
	 */
	public final vehiclelookup.proxies.RequestResponseObj getrequest() throws com.mendix.core.CoreException
	{
		return getrequest(getContext());
	}

	/**
	 * @param context
	 * @return value of request
	 */
	public final vehiclelookup.proxies.RequestResponseObj getrequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		vehiclelookup.proxies.RequestResponseObj result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.request.toString());
		if (identifier != null)
			result = vehiclelookup.proxies.RequestResponseObj.load(context, identifier);
		return result;
	}

	/**
	 * Set value of request
	 * @param request
	 */
	public final void setrequest(vehiclelookup.proxies.RequestResponseObj request)
	{
		setrequest(getContext(), request);
	}

	/**
	 * Set value of request
	 * @param context
	 * @param request
	 */
	public final void setrequest(com.mendix.systemwideinterfaces.core.IContext context, vehiclelookup.proxies.RequestResponseObj request)
	{
		if (request == null)
			getMendixObject().setValue(context, MemberNames.request.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.request.toString(), request.getMendixObject().getId());
	}

	/**
	 * @return value of data
	 */
	public final vehiclelookup.proxies.dataObj getdata() throws com.mendix.core.CoreException
	{
		return getdata(getContext());
	}

	/**
	 * @param context
	 * @return value of data
	 */
	public final vehiclelookup.proxies.dataObj getdata(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		vehiclelookup.proxies.dataObj result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.data.toString());
		if (identifier != null)
			result = vehiclelookup.proxies.dataObj.load(context, identifier);
		return result;
	}

	/**
	 * Set value of data
	 * @param data
	 */
	public final void setdata(vehiclelookup.proxies.dataObj data)
	{
		setdata(getContext(), data);
	}

	/**
	 * Set value of data
	 * @param context
	 * @param data
	 */
	public final void setdata(com.mendix.systemwideinterfaces.core.IContext context, vehiclelookup.proxies.dataObj data)
	{
		if (data == null)
			getMendixObject().setValue(context, MemberNames.data.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.data.toString(), data.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return responseObjMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final vehiclelookup.proxies.ResponseObj that = (vehiclelookup.proxies.ResponseObj) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "VehicleLookUp.ResponseObj";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
