// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package vehiclelookup.proxies;

/**
 * 
 */
public class VehicleSpecificationObj
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject vehicleSpecificationObjMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "VehicleLookUp.VehicleSpecificationObj";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		emissions("emissions"),
		fuel_delivery("fuel_delivery"),
		mpg("mpg"),
		insurance_group("insurance_group"),
		ved_band("ved_band"),
		acceleration("acceleration"),
		top_speed("top_speed"),
		power_output("power_output"),
		valves("valves"),
		cylinders("cylinders"),
		torque("torque"),
		vehicle_specification("VehicleLookUp.vehicle_specification");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public VehicleSpecificationObj(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "VehicleLookUp.VehicleSpecificationObj"));
	}

	protected VehicleSpecificationObj(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject vehicleSpecificationObjMendixObject)
	{
		if (vehicleSpecificationObjMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("VehicleLookUp.VehicleSpecificationObj", vehicleSpecificationObjMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a VehicleLookUp.VehicleSpecificationObj");

		this.vehicleSpecificationObjMendixObject = vehicleSpecificationObjMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'VehicleSpecificationObj.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static vehiclelookup.proxies.VehicleSpecificationObj initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return vehiclelookup.proxies.VehicleSpecificationObj.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static vehiclelookup.proxies.VehicleSpecificationObj initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new vehiclelookup.proxies.VehicleSpecificationObj(context, mendixObject);
	}

	public static vehiclelookup.proxies.VehicleSpecificationObj load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return vehiclelookup.proxies.VehicleSpecificationObj.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of emissions
	 */
	public final String getemissions()
	{
		return getemissions(getContext());
	}

	/**
	 * @param context
	 * @return value of emissions
	 */
	public final String getemissions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.emissions.toString());
	}

	/**
	 * Set value of emissions
	 * @param emissions
	 */
	public final void setemissions(String emissions)
	{
		setemissions(getContext(), emissions);
	}

	/**
	 * Set value of emissions
	 * @param context
	 * @param emissions
	 */
	public final void setemissions(com.mendix.systemwideinterfaces.core.IContext context, String emissions)
	{
		getMendixObject().setValue(context, MemberNames.emissions.toString(), emissions);
	}

	/**
	 * @return value of fuel_delivery
	 */
	public final String getfuel_delivery()
	{
		return getfuel_delivery(getContext());
	}

	/**
	 * @param context
	 * @return value of fuel_delivery
	 */
	public final String getfuel_delivery(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.fuel_delivery.toString());
	}

	/**
	 * Set value of fuel_delivery
	 * @param fuel_delivery
	 */
	public final void setfuel_delivery(String fuel_delivery)
	{
		setfuel_delivery(getContext(), fuel_delivery);
	}

	/**
	 * Set value of fuel_delivery
	 * @param context
	 * @param fuel_delivery
	 */
	public final void setfuel_delivery(com.mendix.systemwideinterfaces.core.IContext context, String fuel_delivery)
	{
		getMendixObject().setValue(context, MemberNames.fuel_delivery.toString(), fuel_delivery);
	}

	/**
	 * @return value of mpg
	 */
	public final String getmpg()
	{
		return getmpg(getContext());
	}

	/**
	 * @param context
	 * @return value of mpg
	 */
	public final String getmpg(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.mpg.toString());
	}

	/**
	 * Set value of mpg
	 * @param mpg
	 */
	public final void setmpg(String mpg)
	{
		setmpg(getContext(), mpg);
	}

	/**
	 * Set value of mpg
	 * @param context
	 * @param mpg
	 */
	public final void setmpg(com.mendix.systemwideinterfaces.core.IContext context, String mpg)
	{
		getMendixObject().setValue(context, MemberNames.mpg.toString(), mpg);
	}

	/**
	 * @return value of insurance_group
	 */
	public final String getinsurance_group()
	{
		return getinsurance_group(getContext());
	}

	/**
	 * @param context
	 * @return value of insurance_group
	 */
	public final String getinsurance_group(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.insurance_group.toString());
	}

	/**
	 * Set value of insurance_group
	 * @param insurance_group
	 */
	public final void setinsurance_group(String insurance_group)
	{
		setinsurance_group(getContext(), insurance_group);
	}

	/**
	 * Set value of insurance_group
	 * @param context
	 * @param insurance_group
	 */
	public final void setinsurance_group(com.mendix.systemwideinterfaces.core.IContext context, String insurance_group)
	{
		getMendixObject().setValue(context, MemberNames.insurance_group.toString(), insurance_group);
	}

	/**
	 * @return value of ved_band
	 */
	public final String getved_band()
	{
		return getved_band(getContext());
	}

	/**
	 * @param context
	 * @return value of ved_band
	 */
	public final String getved_band(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ved_band.toString());
	}

	/**
	 * Set value of ved_band
	 * @param ved_band
	 */
	public final void setved_band(String ved_band)
	{
		setved_band(getContext(), ved_band);
	}

	/**
	 * Set value of ved_band
	 * @param context
	 * @param ved_band
	 */
	public final void setved_band(com.mendix.systemwideinterfaces.core.IContext context, String ved_band)
	{
		getMendixObject().setValue(context, MemberNames.ved_band.toString(), ved_band);
	}

	/**
	 * @return value of acceleration
	 */
	public final String getacceleration()
	{
		return getacceleration(getContext());
	}

	/**
	 * @param context
	 * @return value of acceleration
	 */
	public final String getacceleration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.acceleration.toString());
	}

	/**
	 * Set value of acceleration
	 * @param acceleration
	 */
	public final void setacceleration(String acceleration)
	{
		setacceleration(getContext(), acceleration);
	}

	/**
	 * Set value of acceleration
	 * @param context
	 * @param acceleration
	 */
	public final void setacceleration(com.mendix.systemwideinterfaces.core.IContext context, String acceleration)
	{
		getMendixObject().setValue(context, MemberNames.acceleration.toString(), acceleration);
	}

	/**
	 * @return value of top_speed
	 */
	public final String gettop_speed()
	{
		return gettop_speed(getContext());
	}

	/**
	 * @param context
	 * @return value of top_speed
	 */
	public final String gettop_speed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.top_speed.toString());
	}

	/**
	 * Set value of top_speed
	 * @param top_speed
	 */
	public final void settop_speed(String top_speed)
	{
		settop_speed(getContext(), top_speed);
	}

	/**
	 * Set value of top_speed
	 * @param context
	 * @param top_speed
	 */
	public final void settop_speed(com.mendix.systemwideinterfaces.core.IContext context, String top_speed)
	{
		getMendixObject().setValue(context, MemberNames.top_speed.toString(), top_speed);
	}

	/**
	 * @return value of power_output
	 */
	public final String getpower_output()
	{
		return getpower_output(getContext());
	}

	/**
	 * @param context
	 * @return value of power_output
	 */
	public final String getpower_output(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.power_output.toString());
	}

	/**
	 * Set value of power_output
	 * @param power_output
	 */
	public final void setpower_output(String power_output)
	{
		setpower_output(getContext(), power_output);
	}

	/**
	 * Set value of power_output
	 * @param context
	 * @param power_output
	 */
	public final void setpower_output(com.mendix.systemwideinterfaces.core.IContext context, String power_output)
	{
		getMendixObject().setValue(context, MemberNames.power_output.toString(), power_output);
	}

	/**
	 * @return value of valves
	 */
	public final String getvalves()
	{
		return getvalves(getContext());
	}

	/**
	 * @param context
	 * @return value of valves
	 */
	public final String getvalves(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.valves.toString());
	}

	/**
	 * Set value of valves
	 * @param valves
	 */
	public final void setvalves(String valves)
	{
		setvalves(getContext(), valves);
	}

	/**
	 * Set value of valves
	 * @param context
	 * @param valves
	 */
	public final void setvalves(com.mendix.systemwideinterfaces.core.IContext context, String valves)
	{
		getMendixObject().setValue(context, MemberNames.valves.toString(), valves);
	}

	/**
	 * @return value of cylinders
	 */
	public final String getcylinders()
	{
		return getcylinders(getContext());
	}

	/**
	 * @param context
	 * @return value of cylinders
	 */
	public final String getcylinders(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.cylinders.toString());
	}

	/**
	 * Set value of cylinders
	 * @param cylinders
	 */
	public final void setcylinders(String cylinders)
	{
		setcylinders(getContext(), cylinders);
	}

	/**
	 * Set value of cylinders
	 * @param context
	 * @param cylinders
	 */
	public final void setcylinders(com.mendix.systemwideinterfaces.core.IContext context, String cylinders)
	{
		getMendixObject().setValue(context, MemberNames.cylinders.toString(), cylinders);
	}

	/**
	 * @return value of torque
	 */
	public final String gettorque()
	{
		return gettorque(getContext());
	}

	/**
	 * @param context
	 * @return value of torque
	 */
	public final String gettorque(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.torque.toString());
	}

	/**
	 * Set value of torque
	 * @param torque
	 */
	public final void settorque(String torque)
	{
		settorque(getContext(), torque);
	}

	/**
	 * Set value of torque
	 * @param context
	 * @param torque
	 */
	public final void settorque(com.mendix.systemwideinterfaces.core.IContext context, String torque)
	{
		getMendixObject().setValue(context, MemberNames.torque.toString(), torque);
	}

	/**
	 * @return value of vehicle_specification
	 */
	public final vehiclelookup.proxies.dataObj getvehicle_specification() throws com.mendix.core.CoreException
	{
		return getvehicle_specification(getContext());
	}

	/**
	 * @param context
	 * @return value of vehicle_specification
	 */
	public final vehiclelookup.proxies.dataObj getvehicle_specification(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		vehiclelookup.proxies.dataObj result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.vehicle_specification.toString());
		if (identifier != null)
			result = vehiclelookup.proxies.dataObj.load(context, identifier);
		return result;
	}

	/**
	 * Set value of vehicle_specification
	 * @param vehicle_specification
	 */
	public final void setvehicle_specification(vehiclelookup.proxies.dataObj vehicle_specification)
	{
		setvehicle_specification(getContext(), vehicle_specification);
	}

	/**
	 * Set value of vehicle_specification
	 * @param context
	 * @param vehicle_specification
	 */
	public final void setvehicle_specification(com.mendix.systemwideinterfaces.core.IContext context, vehiclelookup.proxies.dataObj vehicle_specification)
	{
		if (vehicle_specification == null)
			getMendixObject().setValue(context, MemberNames.vehicle_specification.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.vehicle_specification.toString(), vehicle_specification.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return vehicleSpecificationObjMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final vehiclelookup.proxies.VehicleSpecificationObj that = (vehiclelookup.proxies.VehicleSpecificationObj) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "VehicleLookUp.VehicleSpecificationObj";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
