// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package vehiclelookup.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the VehicleLookUp module

	public static void aCT_VehicleLookup(IContext context, vehiclelookup.proxies.RequestObj _lookUpQuery)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("LookUpQuery", _lookUpQuery == null ? null : _lookUpQuery.getMendixObject());
			Core.execute(context, "VehicleLookUp.ACT_VehicleLookup", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static vehiclelookup.proxies.RequestObj dSO_CreateLookup(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "VehicleLookUp.DSO_CreateLookup", params);
			return result == null ? null : vehiclelookup.proxies.RequestObj.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static vehiclelookup.proxies.ResponseObj sUB_VehicleLookup(IContext context, String _registrationNumber)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("RegistrationNumber", _registrationNumber);
			IMendixObject result = (IMendixObject)Core.execute(context, "VehicleLookUp.SUB_VehicleLookup", params);
			return result == null ? null : vehiclelookup.proxies.ResponseObj.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}